HRManagement/Controllers/PositionsController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using HRManagement.DataAccess;
using HRManagement.DataAccess.Models.Models;
using HRManagement.Application;

namespace HRManagement.Controllers
{
    [Authorize]
    public class PositionsController : Controller
    {
        private IPositionService _positionService;
        private IExcelExporter _positionExporter;
        public HrContext db = new HrContext();

        public PositionsController(IPositionService positionService, IExcelExporter positionExporter)
        {
            _positionService = positionService;
            _positionExporter = positionExporter;
        }

        // GET: Positions
        public ActionResult Index()
        {
            var model = new ViewModels.Position.PositionIndexDataViewModel
            {
                Positions = _positionService.GetAllPositions(),
            };

            return View(model);
        }

        [Route("Positions/EmployeesAssignedToPosition/{positionId}")]
        public ActionResult EmployeesAssignedToPosition(int positionId)
        {
            var model = new ViewModels.Position.PositionIndexDataViewModel
            {
                Positions = _positionService.GetAllPositions(),
                EmployeesAssignedToPosition = _positionService.GetEmployeesForPosition(positionId)
            };

            return View("Index", model);
        }

        // GET: Positions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Position position = db.Positions.Find(id);
            if (position == null)
            {
                return HttpNotFound();
            }
            return View(position);
        }

        // GET: Positions/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Positions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Description,Technology,LevelOfExperience")] Position position)
        {
            if (ModelState.IsValid)
            {
                db.Positions.Add(position);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(position);
        }

        // GET: Positions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Position position = db.Positions.Find(id);
            if (position == null)
            {
                return HttpNotFound();
            }
            return View(position);
        }

        // POST: Positions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Description,Technology,LevelOfExperience")] Position position)
        {
            if (ModelState.IsValid)
            {
                db.Entry(position).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(position);
        }

        // GET: Positions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Position position = db.Positions.Find(id);
            if (position == null)
            {
                return HttpNotFound();
            }
            return View(position);
        }

        // POST: Positions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Position position = db.Positions.Find(id);
            db.Positions.Remove(position);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public class PositionExportViewModel
        {
            public int Id { get; set; }
            public string Name { get; set; }
            public string Description { get; set; }
            public string Technology { get; set; }
            public string LevelOfExperience { get; set; }
            public string Employees { get; set; }
        }

        [HttpGet, ActionName("ExportPositions")]
        public FileResult ExportPositions()
        {
            var positions = db.Positions.ToList().Select(x => new PositionExportViewModel
            {
                Id = x.Id,
                Name = x.Name,
                Description = x.Description,
                Technology = x.Technology,
                LevelOfExperience = x.LevelOfExperience.ToString(),
                Employees = x.Employees.Any() ? x.Employees.Select(y => y.FullName).Aggregate((current, next) => current + " , " + next) : "",


            }).ToList();
            var url = _positionExporter.ExportPositions(positions, "positions");
            return File(url, "application/vnd.ms-excel", "positions.xlsx");
        }
    }
}

HRManagement/Views/Positions/Create.cshtml
@model HRManagement.DataAccess.Models.Models.Position

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Position</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Technology, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Technology, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Technology, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LevelOfExperience, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.LevelOfExperience, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LevelOfExperience, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, new { rows = 10, columns = 40 })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HRManagement/Views/Positions/Delete.cshtml
@model HRManagement.DataAccess.Models.Models.Position

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete the "@Html.DisplayFor(model => model.Name)" position?</h3>
<div>
    <hr />

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" />
            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-info" })
        </div>
    }
</div>

HRManagement/Views/Positions/Details.cshtml
@model HRManagement.DataAccess.Models.Models.Position

@{
    ViewBag.Title = "Details";
}

<h2>Job description</h2>

<div>
    <h4>Position</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Technology)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Technology)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LevelOfExperience)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LevelOfExperience)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, new { @class = "btn btn-primary" })
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-info" })
</p>

HRManagement/Views/Positions/Edit.cshtml
@model HRManagement.DataAccess.Models.Models.Position

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Position</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Technology, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Technology, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Technology, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LevelOfExperience, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.LevelOfExperience, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LevelOfExperience, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, new { rows = 10, columns = 40 })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
                @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-info" })
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HRManagement/Views/Positions/Index.cshtml
@model HRManagement.ViewModels.Position.PositionIndexDataViewModel

@{
    ViewBag.Title = "Index";
}
<p>
    @Html.ActionLink("New", "Create", null, new { @class = "btn btn-default" })
    <button onclick="window.location='/Positions/ExportPositions';" class="btn btn-default">Export to Excel</button>
</p>
<h2>List of positions</h2>


<table class="table table table-striped table-responsive">
    <tr>
        <th></th>
        <th>
            @Html.DisplayName("Job title")
        </th>
        <th>
            @Html.DisplayName("Technology")
        </th>
        <th>
            @Html.DisplayName("Level of experience")
        </th>
      
        <th></th>
    </tr>

    @foreach (var item in Model.Positions)
    {
        <tr>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-primary btn-sm" })
                @Html.ActionLink("Job description", "Details", new { id = item.Id }, new { @class = "btn btn-info btn-sm" })
                @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn btn-danger btn-sm" })
                @Html.ActionLink("Employees Assigned", "EmployeesAssignedToPosition", "Positions", new { positionId = @item.Id }, new { @class = "btn btn-success btn-sm" })

            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Technology)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LevelOfExperience)
            </td>
        </tr>
    }
</table>

<br />


@if (Model.EmployeesAssignedToPosition != null)
{
    <h3>List of employees assigned to position</h3>
    <br />
    <table class="table table-condensed table-responsive table-hover table-striped">
        <tr>
            <th>@Html.DisplayName("First Name")</th>
            <th>@Html.DisplayName("Middle Name")</th>
            <th>@Html.DisplayName("Last Name")</th>
        </tr>
        @foreach (var assignedEmployee in Model.EmployeesAssignedToPosition)
        {
            <tr>
                <td>@assignedEmployee.EmployeeFirstName</td>
                <td>@assignedEmployee.EmployeeMiddleName</td>
                <td>@assignedEmployee.EmployeeLastName</td>
            </tr>
        }
    </table>
}