HRManagement/Controllers/EmployeesController.cs
using System.Net;
using System.Web.Mvc;
using HRManagement.DataAccess;
using HRManagement.DataAccess.Models.Models;
using HRManagement.Application;
using HRManagement.ViewModels.Employee;
using System.Linq;
using System;

namespace HRManagement.Controllers
{
    [Authorize]
    public class EmployeesController : Controller
    {
        private IEmployeeService _employeeService;
        public HrContext db = new HrContext();
        private ImageService _imageService;
        private IExcelExporter _employeeExporter;
        private ITrainingService _trainingService;

        public EmployeesController(IEmployeeService employeeService, ImageService imageService, IExcelExporter employeeExporter, ITrainingService trainingService)
        {
            _employeeService = employeeService;
            _imageService = imageService;
            _employeeExporter = employeeExporter;
            _trainingService = trainingService;
        }


        public ActionResult EmployeesAssignedToTraining(int? trainingId)
        {
            var model = new ViewModels.Training.TrainingIndexDataViewModel
            {
                Trainings = _trainingService.GetAllTrainings(),
                EmployeesAssignedToTrainings = _trainingService.GetEmployeesForTraining(trainingId)
            };

            return View("Index", model);
        }
        // GET: Employees
        public ActionResult Index()
        {
            var model = _employeeService.GetAllEmployees();
            return View(model);
        }

        // GET: Employees/Details
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // GET: Employees/Create
        public ActionResult Create()
        {
            var model = _employeeService.GetEmployeeForCreate();
            return View(model);
        }

        // POST: Employees/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateEmployeeViewModel input)
        {
            var employeeId = _employeeService.CreateEmployee(input);
            var imageUrl = _imageService.SaveEmployeeImage(input.ImageUpload, employeeId);
            _employeeService.AttachImage(employeeId, imageUrl);
            return RedirectToAction("Index");

        }

        // GET: Employees/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var model = _employeeService.GetEmployeeForEdit(id);

            return View(model);
        }

        //GET: Employees/5/EditEmploymentInformation
        [HttpGet]
        public ActionResult EditEmploymentInformation(int? employeeId)
        {
            if (employeeId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var model = _employeeService.GetEmploymentInformationForEdit(employeeId);
            return View("~/Views/Employees/GetEmploymentInformationForEdit.cshtml", model);
        }

        //GET: Employees/5/EditFinancialInformation
        [HttpGet]
        public ActionResult EditFinancialInformation(int? employeeId)
        {
            if (employeeId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var model = _employeeService.GetFinancialInformationForEdit(employeeId);
            return View("~/Views/Employees/GetFinancialInformationForEdit.cshtml", model);
        }

        //GET: Employees/5/EditContactInformation
        [HttpGet]
        public ActionResult EditContactInformation(int? employeeId)
        {
            if (employeeId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var model = _employeeService.GetContactInformationForEdit(employeeId);
            return View("~/Views/Employees/GetContactInformationForEdit.cshtml", model);
        }

        // POST: Employees/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EditEmployeeViewModel input)
        {
            _employeeService.SetChangesForEmployee(input.Id, input.PositionId, input.ProjectId, input.LastName, input.MiddleName, input.FirstName, input.DateOfBirth, input.Gender, input.Nationality, input.NationalIdentificationNumber);

            if (input.ImageUpload != null)
            {
                var imageUrl = _imageService.SaveEmployeeImage(input.ImageUpload, input.Id);
                _employeeService.AttachImage(input.Id, imageUrl);
            }

            return RedirectToAction("Index");
        }

        //GET: Employee/5/Trainings
        [HttpGet]
        [Route("employees/{employeeId}/trainings")]
        public ActionResult GetTrainingsForEmployee(int employeeId)
        {
            var model = _employeeService.GetTrainingForEmployee(employeeId);

            return View(model);
        }

        //GET: Employee/5/ContactInformation

        [HttpGet]
        public ActionResult GetContactInformationForEmployee(int employeeId)
        {
            var model = _employeeService.GetContactInformationForEmployee(employeeId);
            return View(model);
        }


        //GET: Employee/5/FinancialInformation

        [HttpGet]
        public ActionResult GetFinancialInformationForEmployee(int employeeId)
        {
            var model = _employeeService.GetFinancialInformationForEmployee(employeeId);
            return View(model);
        }

        //POST: Employees/5/EditEmploymentInformation
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditEmploymentInformation(EditEmploymentInfomationForEmployeeViewModel input)
        {
            _employeeService.EditEmploymentInformation(input.Id, input.EmploymentDate, input.JubileeDate, input.DateForFormalProfessionalCompetence, input.DateForFormalTeachingSkills);
            return RedirectToAction("Index");
        }

        //POST: Employees/5/EditFinancialInformation
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditFinancialInformation(EditFinancialInformationForEmployeeViewModel input)
        {
            _employeeService.EditFinancialInformation(input.Id, input.Salary, input.NextSalaryIncrease, input.AccountNumber, input.Bank);
            return RedirectToAction("Index");
        }


        //POST: Employees/5/EditContactInformation
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditContactInformation(EditContactInformationForEmployeeViewModel input)
        {
            _employeeService.EditContactInformation(input.Id, input.Address, input.City, input.PostalCode, input.State, input.WorkPhone, input.PrivatePhone, input.WorkEmail, input.PrivateEmail);
            return RedirectToAction("Index");
        }

        //GET: Employee/5/EmploymentInformation
        [HttpGet]
        public ActionResult GetEmploymentInformationForEmployee(int employeeId)
        {
            var model = _employeeService.GetEmploymentInformationForEmployee(employeeId);
            return View(model);
        }

        // GET: Employees/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Employee employee = db.Employees.Find(id);
            db.Employees.Remove(employee);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet, ActionName("ExportEmployees")]
        public FileResult ExportEmployees()
        {
            var employees = db.Employees.ToList().Select(x => new EmployeeExportViewModel
            {
                Id = x.Id,
                Name = x.FirstName + " " + x.MiddleName +" " + x.LastName,
                DateOfBirth = x.DateOfBirth,
                Gender = x.Gender.ToString(),
                Nationality = x.Nationality,
                Positions = x.Position.Name,
                Projects = x.Project.Name,
                Trainings = x.Trainings.Any() ? x.Trainings.Select(y => y.Name).Aggregate((current, next) => current + " , " + next) : "",
                Address = x.ContactInformation.Address,
                City = x.ContactInformation.City,
                PostalCode = x.ContactInformation.PostalCode,
                State = x.ContactInformation.State,
                WorkPhone = x.ContactInformation.WorkPhone,
                PrivatePhone = x.ContactInformation.PrivatePhone,
                WorkEmail = x.ContactInformation.WorkEmail,
                PrivateEmail = x.ContactInformation.PrivateEmail,
                EmploymentDate = x.EmploymentInformation.EmploymentDate,
                JubileeDate = x.EmploymentInformation.JubileeDate,
                DateForFormalProfessionalCompetence = x.EmploymentInformation.DateForFormalProfessionalCompetence,
                DateForFormalTeachingSkills = x.EmploymentInformation.DateForFormalTeachingSkills,
                Salary = x.FinancialInformation.Salary,
                NextSalaryIncrease = x.FinancialInformation.NextSalaryIncrease,

HRManagement/Controllers/TrainingController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HRManagement.DataAccess;
using HRManagement.DataAccess.Models.Models;
using HRManagement.Application;

namespace HRManagement.Controllers
{
    [Authorize]
    public class TrainingController : Controller
    {
        private ITrainingService _trainingService;
        private IExcelExporter _trainingExporter;
        private HrContext db = new HrContext();
        public TrainingController(ITrainingService trainingService, IExcelExporter trainingExporter)
        {
            _trainingService = trainingService;
            _trainingExporter = trainingExporter;
        }

        // GET: Training
        public ActionResult Index()
        {
            var model = new ViewModels.Training.TrainingIndexDataViewModel
            {
                Trainings = _trainingService.GetAllTrainings(),
            };

            return View(model);
        }

        public ActionResult EmployeesAssignedToTraining(int? trainingId)
        {
            var model = new ViewModels.Training.TrainingIndexDataViewModel
            {
                Trainings = _trainingService.GetAllTrainings(),
                EmployeesAssignedToTrainings = _trainingService.GetEmployeesForTraining(trainingId)
            };

            return View("Index", model);
        }

        // GET: Training/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Training training = db.Trainings.Find(id);
            if (training == null)
            {
                return HttpNotFound();
            }
            return View(training);
        }

        // GET: Training/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Training/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,StartDate,EndDate,Status")] Training training)
        {
            if (ModelState.IsValid)
            {
                db.Trainings.Add(training);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(training);
        }

        // GET: Training/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Training training = db.Trainings.Find(id);
            if (training == null)
            {
                return HttpNotFound();
            }
            return View(training);
        }

        // POST: Training/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,StartDate,EndDate,Status")] Training training)
        {
            if (ModelState.IsValid)
            {
                db.Entry(training).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(training);
        }

        // GET: Training/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Training training = db.Trainings.Find(id);
            if (training == null)
            {
                return HttpNotFound();
            }
            return View(training);
        }

        // POST: Training/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Training training = db.Trainings.Find(id);
            db.Trainings.Remove(training);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public class TrainingExportViewModel
        {
            public int Id { get; set; }
            public string Name { get; set; }
            public DateTime StartDate { get; set; }
            public DateTime EndDate { get; set; }
            public string Status { get; set; }
            public string Employees { get; set; }
        }

        [HttpGet, ActionName("ExportTrainings")]
        public FileResult ExportTrainings()
        {
            var trainings = db.Trainings.ToList().Select(x => new TrainingExportViewModel
            {
                Id = x.Id,
                Name = x.Name,
                StartDate = x.StartDate,
                EndDate = x.EndDate,
                Status = x.Status.ToString(),
                Employees = x.Employees.Any() ? x.Employees.Select(y => y.FullName).Aggregate((current, next) => current + " , " + next) : "",
                

            }).ToList();
            var url = _trainingExporter.ExportTrainings(trainings, "trainings");
            return File(url, "application/vnd.ms-excel", "trainings.xlsx");
        }
    }
}

HRManagement/Views/Employees/Create.cshtml
@model HRManagement.ViewModels.Employee.CreateEmployeeViewModel


@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create","Employees",FormMethod.Post,new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Employee</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MiddleName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MiddleName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MiddleName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Gender, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nationality, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nationality, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nationality, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NationalIdentificationNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NationalIdentificationNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NationalIdentificationNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Languages, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Languages, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Languages, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Position", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.DropDownListFor(model => model.PositionId, Model.Positions.Select(x => new SelectListItem { Text = x.Name, Value = x.Id.ToString()}), htmlAttributes: new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Project", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.DropDownListFor(model => model.ProjectId, Model.Projects.Select(x => new SelectListItem { Text = x.Name, Value = x.Id.ToString() }), htmlAttributes: new { @class = "form-control" })
            </div>
        </div>

        <h4>Financial information</h4>
        <hr />
        <div class="form-group">
            @Html.LabelFor(model => model.Salary, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Salary, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Salary, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NextSalaryIncrease, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NextSalaryIncrease, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NextSalaryIncrease, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AccountNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AccountNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AccountNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Bank, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Bank, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Bank, "", new { @class = "text-danger" })
            </div>
        </div>

        <h4>Contact information</h4>
        <hr />
        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PostalCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostalCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PostalCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WorkPhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WorkPhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WorkPhone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PrivatePhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PrivatePhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PrivatePhone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WorkEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WorkEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WorkEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WorkPhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WorkPhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WorkPhone, "", new { @class = "text-danger" })
            </div>
        </div>

        <h4>Employment information</h4>
        <hr />
        <div class="form-group">
            @Html.LabelFor(model => model.EmploymentDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmploymentDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmploymentDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.JubileeDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.JubileeDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.JubileeDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateForFormalProfessionalCompetence, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateForFormalProfessionalCompetence, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateForFormalProfessionalCompetence, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateForFormalTeachingSkills, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateForFormalTeachingSkills, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateForFormalTeachingSkills, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.ImageUpload, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="ImageUpload" for="ImageUpload" />
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HRManagement/Views/Employees/Delete.cshtml
@model HRManagement.DataAccess.Models.Models.Employee

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete @Html.DisplayFor(model => model.LastName) @Html.DisplayFor(model => model.MiddleName) @Html.DisplayFor(model => model.FirstName)?</h3>
<div>
    
   


    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> 
            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-info" })
        </div>
    }
</div>

HRManagement/Views/Employees/GetTrainingsForEmployee.cshtml
@model HRManagement.ViewModels.Employee.GetTrainingForEmployeeViewModel
@{
    ViewBag.Title = "Trainings";
}

<h2>Details</h2>

@Html.Partial("~/Views/Employees/Partials/_EmployeeDetailsSidebar.cshtml", new HRManagement.Models.Partials.EmployeeDetailsSidebarViewModel { ActiveTab = "trainings", EmployeeId = Model.EmployeeId })

<div>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayName("Name")
            </th>
            <th>
                @Html.DisplayName("StartDate")
            </th>
            <th>
                @Html.DisplayName("EndDate")
            </th>
            <th>
                @Html.DisplayName("Status")
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model.Trainings)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StartDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EndDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
            </tr>
        }

    </table>
</div>

<p>
    @Html.ActionLink("Edit","Edit","Training", new { id = Model.Trainings.Select(x => x.Id) }, new { @class = "btn btn-primary" })
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-info" })
</p>